# Generated by Django 3.2 on 2021-11-26 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booking_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.bookinginfo')),
            ],
            options={
                'verbose_name': 'Booking Reservations',
                'ordering': ('end_date', 'start_date'),
            },
        ),
    ]
